# Generated by Django 5.1 on 2024-08-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only')], default='public', max_length=10),
        ),
    ]
